---
apiVersion: v1
kind: Namespace
metadata:
  name: ps-ns
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: aloeda-product-service-config-map
  namespace: ps-ns
data:
  ENV_APP_NAME: "aloeda-product-service"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aloeda-product-service
  namespace: ps-ns
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: aloeda-product-service
  template:
    metadata:
      labels:
        app: aloeda-product-service
    spec:
      initContainers:
        - name: init-myservice
          image: busybox:1.28
          command: [ 'sh', '-c', "printenv" ]
      containers:
        - name: aloeda-product-service
          image: ojoadeolagabriel/aloeda-product-service:latest
          livenessProbe:
            httpGet:
              path: /health
              port: 12345
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 12345
            initialDelaySeconds: 30
            periodSeconds: 10
          ports:
            - containerPort: 12345
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: aloeda-product-service-config-map
---
apiVersion: v1
kind: Service
metadata:
  name: aloeda-product-service-service
  namespace: ps-ns
spec:
  selector:
    app: aloeda-product-service
  ports:
    - port: 50003
      targetPort: 12345
  type: LoadBalancer